"""Общие утилиты проекта INDCTRL."""

from control_common.constants import (
    DETAIL_STATE_DEFECT,
    DETAIL_STATE_UNDEFINED,
    DETAIL_STATE_WORKING,
    ROLE_ADMIN,
    ROLE_DIRECTOR,
    ROLE_MANAGER,
    ROLE_WORKER,
    SERVICE_AUTH,
    SERVICE_CONTROL_WEB,
    SERVICE_EVENT,
    WORK_STATUS_ACTIVE,
    WORK_STATUS_CANCELLED,
    WORK_STATUS_EXPIRED,
    WORK_STATUS_FINISHED,
)

__all__ = [
    "DETAIL_STATE_DEFECT",
    "DETAIL_STATE_UNDEFINED",
    "DETAIL_STATE_WORKING",
    "ROLE_ADMIN",
    "ROLE_DIRECTOR",
    "ROLE_MANAGER",
    "ROLE_WORKER",
    "SERVICE_AUTH",
    "SERVICE_CONTROL_WEB",
    "SERVICE_EVENT",
    "WORK_STATUS_ACTIVE",
    "WORK_STATUS_CANCELLED",
    "WORK_STATUS_EXPIRED",
    "WORK_STATUS_FINISHED",
]
